### ISSUE TITLE
Status Code 302 Redirect Not Handled

### ISSUE THREAD

**Issue by benjaminluehrsppfa** [JPipkin/SFDC-Record-Type-Picklist#1]
Awesome components here! Thanks! One note is that at least in my Sandbox right now, I'm getting a Status Code 302, which is for a redirect, so I needed to add the code snippet found [here](https://salesforce.stackexchange.com/questions/136811/httpcallout-error-statuscode-302) right after the initial call and then it works perfectly.

**Comment by JPipkin** [comment]
@benjaminluehrsppfa I'm glad you like it! The 302 status code indicates that the uri defined in the named credentials is in the wrong format. "https://[domain].**lightning**.salesforce.com" instead of "https://[domain].**my**.salesforce.com". It would be better to correct that issue rather than handle the 302 error to save on API call limits. Thanks!

**Comment by benjaminluehrsppfa** [comment]
@JPipkin That makes total sense! However, based on the redirect I'm getting back, the correct format is https://[domain].[server].my.salesforce.com (though server might only be necessary in Sandbox), so it looks like your original instructions are correct with the note that domain should include server if in Sandbox. Sorry for the confusion!
